# Generated by Django 5.1.5 on 2025-02-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default=0, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
