# Generated by Django 5.1.5 on 2025-02-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_brand_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='title',
        ),
    ]
